### ISSUE TITLE
Update password in profile route

### ISSUE THREAD

**Issue by stevenpersia** [stevenpersia/hc-back-end#2]
Hi team !

I would like to have your advices about this part of code.
In profile page, i've got a route where I update user's password.

Is it better to add lines 33 to 35 and line 45 in my condition (line 41) ?

Above you can see concerned code :
https://github.com/stevenpersia/hc-back-end/blob/6516064fc04bd949d5cee49e75c8509409f2d15f/routes/settings.js#L30-L50

Thank you for your help 👍

**Comment by gashmal** [comment]
done
